### ISSUE TITLE
Why go-upf ?

### ISSUE THREAD

**Issue by mohammedyaqub** [free5gc/go-upf#20]
Hi, 

I would like to know why go-upf  implementation ?
Is it run only in user space without interaction of the kernel ?

Thanks.

**Comment by free5gc-org** [comment]
go-upf still need interact with kernel. It is easy to support SBI in the future.

**Comment by mohammedyaqub** [comment]
Thank you for response.

So basically it's mean go-upf also depends upon kernel for packet processing correct.
