### ISSUE TITLE
No CreatedPDR in SessionEstablishmentResponse?

### ISSUE THREAD

**Issue by zyddnys** [free5gc/go-upf#34]
Hi free5gc, 
It seems that there is no CreatedPDR IE when sending SessionEstablishmentResponse back to the SMF. The spec 29244 says that if the SMF request to allocate a local F-TEID then the UPF shall allocate a local F-TEID and send back to SMF in a CreatedPDR IE.
Many SMF will ask the UPF to allocate TEID.
Am i correct about this behavior? why is there no CreatedPDR in SessionEstablishmentResponse in go-upf?

**Comment by andy89923** [comment]
Sorry for the late reply.  You could check #45 .
