### ISSUE TITLE
PFCP Session Establishment Response is encoded incorrectly

### ISSUE THREAD

**Issue by yoursunny** [free5gc/go-upf#54]
I notice that free5GC UPF is encoding **PFCP Session Establishment Response** message incorrectly.
According to [TS 129 244](https://www.etsi.org/deliver/etsi_ts/129200_129299/129244/16.04.00_60/ts_129244v160400p.pdf) section 7.5.3.1, the PFCP Session Establishment Response message may contain **Created PDR** IE (IE Type 8).
However, the PFCP Session Establishment Response message sent by free5GC UPF contains **Create PDR** IE (IE Type 1), which is only allowed in PFCP Session Establishment/Modification Request.

Packet trace: [n4n3-free5gc.zip](https://github.com/user-attachments/files/16180525/n4n3-free5gc.zip)
Frame 38 has the incorrectly encoded packet:

```text
Packet Forwarding Control Protocol
    Flags: 0x21, SEID (S)
    Message Type: PFCP Session Establishment Response (51)
    Length: 235
    SEID: 0x0000000000000001
    Sequence Number: 4
    Spare: 0
    Node ID : IPv4 address: 172.25.195.6
    Cause : Request accepted(success)
    F-SEID : SEID: 0x0000000000000001, IPv4 172.25.195.6
    Create PDR : [Grouped IE]: PDR ID: 2
        IE Type: Create PDR (1)
        IE Length: 188
        Create PDR : [Grouped IE]: PDR ID: 1
        Create PDR : [Grouped IE]: PDR ID: 2
    [Response To: 37]
    [Response Time: 0.002743378 seconds]
```

**Comment by ian60509** [comment]
This is indeed a bug in our program. We will fix it as soon as possible. Thank you for reporting it.

**Comment by andy89923** [comment]
#58
